"""Remove speaker from dialog

Revision ID: a378ad10d13d
Revises: dafc5e30ce62
Create Date: 2024-11-28 22:55:20.337101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a378ad10d13d'
down_revision: Union[str, None] = 'dafc5e30ce62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogs', 'speaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('speaker', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
