"""Update updated_at and created_at

Revision ID: dafc5e30ce62
Revises: ac33d76e336b
Create Date: 2024-11-28 21:55:28.004319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafc5e30ce62'
down_revision: Union[str, None] = 'ac33d76e336b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
